<a href="https://colab.research.google.com/github/LNBMS/dev/blob/main/placement_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("navinpatidar/indian-student-placement-data")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/navinpatidar/indian-student-placement-data/1.archive...

100%|██████████| 28.3k/28.3k [00:00<00:00, 29.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/navinpatidar/indian-student-placement-data/versions/1

In [ ]:
import kagglehub
import pandas as pd
import os

# Download dataset
path = kagglehub.dataset_download("navinpatidar/indian-student-placement-data")

print("Dataset folder:", path)

# See files downloaded
print(os.listdir(path))

# Read the CSV file
file_path = os.path.join(path, "Indian_student_placement_dataset.csv")

df = pd.read_csv(file_path)

df.head()

Using Colab cache for faster access to the 'indian-student-placement-data' dataset.
Dataset folder: /kaggle/input/indian-student-placement-data
['indian_student_placement_data.csv']

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/indian-student-placement-data/Indian_student_placement_dataset.csv'

In [ ]:
import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download("navinpatidar/indian-student-placement-data")

print("Dataset folder:", path)
print("Files in folder:", os.listdir(path))

Using Colab cache for faster access to the 'indian-student-placement-data' dataset.
Dataset folder: /kaggle/input/indian-student-placement-data
Files in folder: ['indian_student_placement_data.csv']

In [ ]:
file_path = os.path.join(path, "Indian_student_placement_dataset.csv")

df = pd.read_csv(file_path)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/indian-student-placement-data/Indian_student_placement_dataset.csv'

In [ ]:
import kagglehub
import os
import pandas as pd

# Download dataset
path = kagglehub.dataset_download("navinpatidar/indian-student-placement-data")

# Find CSV file
csv_file = [f for f in os.listdir(path) if f.endswith(".csv")][0]

# Load dataset
df = pd.read_csv(os.path.join(path, csv_file))

# Display first 5 records
df.head()

Using Colab cache for faster access to the 'indian-student-placement-data' dataset.

,Name,Email,Course,Branch,Graduation Year,Company,Job Role,Salary (INR),Location,Placement Date
0,Yasmin Yadav,ibrar@gmail.com,B.Sc,Civil,2020,Google,Web Developer,808813,Delhi,2024-08-14
1,Ritvik Kalla,stuvansaxena@hotmail.com,BCA,EEE,2022,Accenture,Support Engineer,309179,Bangalore,2025-02-05
2,Rasha Dewan,neysasule@yahoo.com,B.Com,IT,2023,Accenture,Software Engineer,711614,Hyderabad,2024-03-09
3,Indranil Sawhney,sekhonraghav@hotmail.com,BBA,Mechanical,2024,TCS,Consultant,717444,Mumbai,2023-10-18
4,Aarav Konda,kurianshray@bava.com,BCA,IT,2023,IBM,Data Analyst,1171796,Hyderabad,2023-11-09

In [ ]:
print('Current columns in DataFrame:', df.columns.tolist())
#understand the datset
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Shape:",df.shape)
print("cols:",df.columns)
df.info()
df.describe(include="object")
#display random records
print("display random records:")
df.sample(10)

Current columns in DataFrame: ['Name', 'Email', 'Course', 'Branch', 'Graduation Year', 'Company', 'Job Role', 'Salary (INR)', 'Location', 'Placement Date']
Number of rows: 1000
Number of columns: 10
Shape: (1000, 10)
cols: Index(['Name', 'Email', 'Course', 'Branch', 'Graduation Year', 'Company',
       'Job Role', 'Salary (INR)', 'Location', 'Placement Date'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             1000 non-null   object
 1   Email            1000 non-null   object
 2   Course           1000 non-null   object
 3   Branch           1000 non-null   object
 4   Graduation Year  1000 non-null   int64
 5   Company          1000 non-null   object
 6   Job Role         1000 non-null   object
 7   Salary (INR)     1000 non-null   int64
 8   Location         1000 non-null   object
 9   Placement Date   1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.3+ KB
display random records:

Series([], dtype: float64)

In [ ]:
#display datatypes
df.dtypes

Name               object
Email              object
Course             object
Branch             object
Graduation Year     int64
Company            object
Job Role           object
Salary (INR)        int64
Location           object
Placement Date     object
dtype: object

In [ ]:
df.dtypes.value_counts()

object    8
int64     2
Name: count, dtype: int64

In [ ]:
#check missing values
df.isnull().sum()

Name               0
Email              0
Course             0
Branch             0
Graduation Year    0
Company            0
Job Role           0
Salary (INR)       0
Location           0
Placement Date     0
dtype: int64

In [ ]:
#percentage of missing values
missing_percentage = df.isnull().sum() / df.shape[0] * 100
missing_percentage

Name               0.0
Email              0.0
Course             0.0
Branch             0.0
Graduation Year    0.0
Company            0.0
Job Role           0.0
Salary (INR)       0.0
Location           0.0
Placement Date     0.0
dtype: float64

In [ ]:
#display only colums which is having missing values
missing_percentage[missing_percentage>0]

Series([], dtype: float64)

In [ ]:
#check the duplicate records
df.duplicated().sum()

np.int64(0)

In [ ]:
#display duplicate records
df[df.duplicated()]
#df

Empty DataFrame
Columns: [Name, Email, Course, Branch, Graduation Year, Company, Job Role, Salary (INR), Location, Placement Date]
Index: []

In [ ]:
#remove duplicates
df=df.drop_duplicates()
df

,Name,Email,Course,Branch,Graduation Year,Company,Job Role,Salary (INR),Location,Placement Date
0,Yasmin Yadav,ibrar@gmail.com,B.Sc,Civil,2020,Google,Web Developer,808813,Delhi,2024-08-14
1,Ritvik Kalla,stuvansaxena@hotmail.com,BCA,EEE,2022,Accenture,Support Engineer,309179,Bangalore,2025-02-05
2,Rasha Dewan,neysasule@yahoo.com,B.Com,IT,2023,Accenture,Software Engineer,711614,Hyderabad,2024-03-09
3,Indranil Sawhney,sekhonraghav@hotmail.com,BBA,Mechanical,2024,TCS,Consultant,717444,Mumbai,2023-10-18
4,Aarav Konda,kurianshray@bava.com,BCA,IT,2023,IBM,Data Analyst,1171796,Hyderabad,2023-11-09
...,...,...,...,...,...,...,...,...,...,...
995,Vivaan Mallick,vohrataimur@yahoo.com,BA,CSE,2020,Capgemini,Web Developer,1190049,Bangalore,2025-03-28
996,Arnav Kuruvilla,trisha23@dutta.biz,BBA,CSE,2020,Wipro,Data Analyst,543972,Mumbai,2024-10-05
997,Lavanya Chopra,shayakbhalla@gmail.com,BCA,CSE,2024,Capgemini,System Engineer,426980,Delhi,2024-04-29
998,Piya Kaur,mamooty59@yahoo.com,B.Com,ECE,2022,TCS,Web Developer,1100354,Pune,2023-01-21
999,Faiyaz Talwar,chadvivaan@yahoo.com,B.Com,Civil,2022,Google,Web Developer,756215,Chennai,2023-01-28

In [ ]:
#verify
df.duplicated().sum()

np.int64(0)

In [ ]:

#rename col
print("Cols:",df.columns)
# The following rename operations are commented out because the source columns 'CGPA', 'PlacementStatus', '10th percentage', '12th percentage', 'Degree Percentage' do not exist in the DataFrame.
# Please verify the correct column names from `df.columns` above and modify the rename operations accordingly.
df=df.rename(columns={"CGPA": "CGPA","PlacementStatus":"Placement_Status"})
#rename several col
df=df.rename(columns={
    "10th percentage":"Percentage_10th",
    "12th percentage":"Percentage_12th",
    "Degree Percentage":"Degree_Percentage"
 })

# The following lines are commented out as they refer to non-existent columns (CGPA, Placement_Status, Degree_Percentage, Specialization).
# To fix this, please use existing column names from the `df.columns` output.
df.columns
#select single col
df["CGPA"]
#Select multiple col
df[ [
     "CGPA",
    "Degree_Percentage",
    "Placement_Status"
 ]
    ]
#using loc
df.loc[:,["CGPA","Degree_Percentage"]]
#specify rows
df.loc[0:10,["CGPA","Degree_Percentage"]]
#using iloc
df.iloc[0:10,0:5]
#specific row
df.iloc[5]
# students having cgpa greater than 8
df[df["CGPA"]>8]
#Students with CGPA >8 and degree percentage >70
df[
    (df["CGPA"]>8) &
    (df["Degree_Percentage"]>70)
 ]
#using isin()
df[
    df["Specialization"].isin(
       ["Computer Science","Information Technology"]
   )
 ]
#using between()
#Students whose CGPA is between 7 and 8.5
df[
    df["CGPA"].between(7,8.5)
 ]
#sorting -highest cgpa first
df.sort_values(
   by="CGPA",
    ascending=False
 ).head(10)
#Sorting using multiple col
df.sort_values(
    by=["Specialization","CGPA"],
    ascending=[True, False]
 )
#value_counts()
df["Placement_Status"].value_counts()
#display unique value_counts
df["Placement_Status"].unique()
#display no of unique values
df["Placement_Status"].nunique()
#percentage
#df["Placement"]

Cols: Index(['Name', 'Email', 'Course', 'Branch', 'Graduation Year', 'Company',
       'Job Role', 'Salary (INR)', 'Location', 'Placement Date'],
      dtype='object')

KeyError: 'CGPA'